// Expanded ZIP export — adds deploy configs, package.json, gitignore, manifest, robots, sitemap, README.
import JSZip from 'jszip';
import type { ProjectRecord, ProjectVersion } from './projectStore';
import { buildValidationReport } from './validationReport';

export async function exportProjectZip(project: ProjectRecord, version: ProjectVersion) {
  const zip = new JSZip();
  const slug = project.name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '') || 'site';

  zip.file('index.html', version.html);
  zip.file('robots.txt', 'User-agent: *\nAllow: /\nSitemap: /sitemap.xml\n');
  zip.file('sitemap.xml', `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemap.org/schemas/sitemap/0.9">\n  <url><loc>/</loc><changefreq>weekly</changefreq><priority>1.0</priority></url>\n</urlset>\n`);
  zip.file('manifest.webmanifest', JSON.stringify({
    name: project.name, short_name: project.name.slice(0, 12),
    start_url: '/', display: 'standalone', background_color: '#ffffff', theme_color: '#000000',
    icons: [{ src: '/favicon.png', sizes: '192x192', type: 'image/png' }],
  }, null, 2));
  zip.file('.gitignore', 'node_modules\n.DS_Store\ndist\n.env\n');
  zip.file('package.json', JSON.stringify({
    name: slug, version: '1.0.0', private: true,
    scripts: { start: 'npx serve .', deploy: 'echo "Drop this folder on Netlify, Vercel, or Cloudflare Pages."' },
  }, null, 2));
  zip.file('vercel.json', JSON.stringify({ cleanUrls: true, trailingSlash: false }, null, 2));
  zip.file('netlify.toml', `[build]\n  publish = "."\n\n[[headers]]\n  for = "/*"\n  [headers.values]\n    X-Frame-Options = "DENY"\n    X-Content-Type-Options = "nosniff"\n    Referrer-Policy = "strict-origin-when-cross-origin"\n`);
  zip.file('_headers', `/*\n  X-Content-Type-Options: nosniff\n  Referrer-Policy: strict-origin-when-cross-origin\n  Permissions-Policy: geolocation=(), microphone=()\n`);
  zip.file('_redirects', `/* /index.html 200\n`);

  zip.file('README.md',
`# ${project.name}

Generated by **kinging.dev** — AI Website Builder.

## Quick start
\`\`\`bash
npx serve .
# or just open index.html in your browser
\`\`\`

## Deploy in 30 seconds
- **Netlify**: drag this folder onto https://app.netlify.com/drop — \`netlify.toml\` is included
- **Vercel**: \`npx vercel --prod\` from this folder — \`vercel.json\` is included
- **Cloudflare Pages**: connect your git repo or upload this folder — \`_headers\` and \`_redirects\` are included
- **GitHub Pages**: commit to a repo and enable Pages

## Files
| File | Purpose |
|---|---|
| \`index.html\` | Your full single-file site |
| \`manifest.webmanifest\` | PWA install metadata |
| \`robots.txt\` / \`sitemap.xml\` | SEO basics |
| \`vercel.json\` / \`netlify.toml\` / \`_headers\` / \`_redirects\` | Deploy presets |
| \`package.json\` | npm metadata + local serve script |
| \`validation-report.md\` | Accessibility, SEO, performance audit |

## Versions
- Active: ${version.label}
- Created: ${new Date(version.createdAt).toISOString()}
- Original prompt: ${project.initialPrompt}
`);

  if (version.validation) zip.file('validation-report.md', buildValidationReport(project, version));

  const blob = await zip.generateAsync({ type: 'blob', compression: 'DEFLATE' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${slug}-${version.label.replace(/\s.*/, '')}.zip`;
  a.click();
  setTimeout(() => URL.revokeObjectURL(url), 60000);
}
