// Bundle a project as a downloadable ZIP including index.html, README, and validation report.
import JSZip from 'jszip';
import type { ProjectRecord, ProjectVersion } from './projectStore';
import { buildValidationReport } from './validationReport';

export async function exportProjectZip(project: ProjectRecord, version: ProjectVersion) {
  const zip = new JSZip();
  zip.file('index.html', version.html);
  zip.file('README.md',
`# ${project.name}

Generated by **kinging.dev** — AI Website Builder.

## Files
- \`index.html\` — your full site, single file. Open in a browser or deploy to any static host.
- \`validation-report.md\` — accessibility, SEO, performance & security audit.

## Deploy
- **Netlify / Vercel**: drag this folder onto the dashboard.
- **GitHub Pages**: commit to a repo and enable Pages.
- **Cloudflare Pages / Render**: connect the repo or upload the folder.

## Versions
- Active: ${version.label}
- Created: ${new Date(version.createdAt).toISOString()}

> Original prompt: ${project.initialPrompt}
`);
  if (version.validation) {
    zip.file('validation-report.md', buildValidationReport(project, version));
  }
  zip.file('robots.txt', 'User-agent: *\nAllow: /\n');
  const blob = await zip.generateAsync({ type: 'blob', compression: 'DEFLATE' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${project.name.toLowerCase().replace(/\s+/g, '-')}-${version.label.replace(/\s.*/, '')}.zip`;
  a.click();
  setTimeout(() => URL.revokeObjectURL(url), 60000);
}
